import React from 'react';

const Article08 = () => {
    return (
        <div className="ArticleContent">
            <h1 className="entry-title">¿Cómo realizo el cambio de domicilio fiscal en el SAT?</h1>
            <br />
            <p>¿Necesitas realizar Cambio de Domicilio Fiscal? En <a rel="noreferrer noopener" aria-label="docDigitales (abre en una nueva pestaña)" href="https://www.docdigitales.com/" target="_blank">docDigitales</a> te decimos cómo puedes realizar paso a paso un cambio de domicilio fiscal para tu RFC de una forma sencilla para ello necesitas contar con tu Firma Electrónica (FIEL) o la CIEC.</p>
            <br />
            <p><strong>1.-</strong> Accede a la página del <a rel="noreferrer noopener" aria-label="SAT (abre en una nueva pestaña)" href="https://www.sat.gob.mx/home" target="_blank"><strong>SAT</strong></a> en el apartado de <a rel="noreferrer noopener" aria-label="Tramites (abre en una nueva pestaña)" href="https://www.sat.gob.mx/tramites/30357/realiza-tu-cambio-de-domicilio-en-el-rfc" target="_blank"><strong>Trámites</strong></a> (realiza tu cambio de domicilio en el RFC, después <a rel="noreferrer noopener" aria-label="Iniciar (abre en una nueva pestaña)" href="https://www.sat.gob.mx/tramites/login/30357/realiza-tu-cambio-de-domicilio-en-el-rfc" target="_blank"><strong>Iniciar</strong></a> te dará la opción de ingresar con tu (<strong>FIEL</strong>) Firma Electrónica o la <strong>CIEC</strong>. Una vez agregada la información das clic en <strong>Enviar</strong></p>
            <br />
            <div className="centerImage"><figure className="aligncenter is-resized"><img src="https://www.docdigitales.com/blog/wp-content/uploads/2021/07/1-5.png" alt="1 5" className="wp-image-6420" width="547" height="416" srcset="https://www.docdigitales.com/blog/wp-content/uploads/2021/07/1-5.png 748w, https://www.docdigitales.com/blog/wp-content/uploads/2021/07/1-5-300x228.png 300w" sizes="(max-width: 547px) 100vw, 547px" /></figure></div>
            <p><strong>2.-</strong> En caso de ser <strong>Persona Física</strong> al ingresar ya te estará dando toda la información capturada, pero si es <strong>Persona Moral</strong> será necesario agregar el RFC del representante legal de la empresa.</p>
            <br />
            <p><strong>3.- La Fecha de Movimiento: No puede ser anterior a 10 días hábiles- La Fecha de Movimiento no puede ser mayor a 5 días hábiles de la fecha actual</strong>. En caso de ser Persona Física se debe agregar la fecha del cambio de movimiento. Solo los recuadros marcados con <strong>*</strong> son obligatorios.</p>
            <br />
            <p><strong>4.-</strong> Una vez realizados todos los cambios necesarios da clic en <strong>Continuar</strong>.</p>
            <br />
            <div className="centerImage"><figure className="aligncenter is-resized"><img src="https://www.docdigitales.com/blog/wp-content/uploads/2021/07/2.png" alt="2" className="wp-image-6422" width="736" height="392" srcset="https://www.docdigitales.com/blog/wp-content/uploads/2021/07/2.png 976w, https://www.docdigitales.com/blog/wp-content/uploads/2021/07/2-300x160.png 300w, https://www.docdigitales.com/blog/wp-content/uploads/2021/07/2-768x410.png 768w" sizes="(max-width: 736px) 100vw, 736px" /></figure></div>
            <div className="centerImage"><figure className="aligncenter is-resized"><img src="https://www.docdigitales.com/blog/wp-content/uploads/2021/07/3.3.jpg" alt="3.3" className="wp-image-6423" width="797" height="436" srcset="https://www.docdigitales.com/blog/wp-content/uploads/2021/07/3.3.jpg 968w, https://www.docdigitales.com/blog/wp-content/uploads/2021/07/3.3-300x164.jpg 300w, https://www.docdigitales.com/blog/wp-content/uploads/2021/07/3.3-768x420.jpg 768w" sizes="(max-width: 797px) 100vw, 797px" /></figure></div>
            <div className="centerImage"><figure className="aligncenter is-resized"><img src="https://www.docdigitales.com/blog/wp-content/uploads/2021/07/4.1.jpg" alt="4.1" className="wp-image-6424" width="777" height="241" srcset="https://www.docdigitales.com/blog/wp-content/uploads/2021/07/4.1.jpg 977w, https://www.docdigitales.com/blog/wp-content/uploads/2021/07/4.1-300x93.jpg 300w, https://www.docdigitales.com/blog/wp-content/uploads/2021/07/4.1-768x239.jpg 768w" sizes="(max-width: 777px) 100vw, 777px" /></figure></div>
            <p><strong>5.-</strong> Ya que confirmaste la información te indicará que <strong>Ha concluido la captura</strong> y podrás ingresar en <strong>confirmar</strong> para visualizar que la información agregada sea la correcta.</p>
            <br />
            <div className="centerImage"><figure className="aligncenter is-resized"><img src="https://www.docdigitales.com/blog/wp-content/uploads/2021/07/5.png" alt="5" className="wp-image-6425" width="448" height="128" srcset="https://www.docdigitales.com/blog/wp-content/uploads/2021/07/5.png 946w, https://www.docdigitales.com/blog/wp-content/uploads/2021/07/5-300x86.png 300w, https://www.docdigitales.com/blog/wp-content/uploads/2021/07/5-768x220.png 768w" sizes="(max-width: 448px) 100vw, 448px" /></figure></div>
            <p><strong>6.-</strong> Será necesario verificar que toda la información que ingresaste esté correcta ya que al dar clic en <strong>Confirmar</strong> ésta no podrá ser modificada. En caso de que contenga algún error da clic en <strong>Cancelar </strong>para regresar al punto <strong>no. 4</strong> y modifica el registro. </p>
            <br />
            <div className="centerImage"><figure className="aligncenter is-resized"><img src="https://www.docdigitales.com/blog/wp-content/uploads/2021/07/6.1.jpg" alt="6.1" className="wp-image-6426" width="721" height="333" srcset="https://www.docdigitales.com/blog/wp-content/uploads/2021/07/6.1.jpg 955w, https://www.docdigitales.com/blog/wp-content/uploads/2021/07/6.1-300x139.jpg 300w, https://www.docdigitales.com/blog/wp-content/uploads/2021/07/6.1-768x355.jpg 768w" sizes="(max-width: 721px) 100vw, 721px" /></figure></div>
            <div className="centerImage"><figure className="aligncenter is-resized"><img src="https://www.docdigitales.com/blog/wp-content/uploads/2021/07/7.1.jpg" alt="7.1" className="wp-image-6429" width="730" height="300" srcset="https://www.docdigitales.com/blog/wp-content/uploads/2021/07/7.1.jpg 969w, https://www.docdigitales.com/blog/wp-content/uploads/2021/07/7.1-300x123.jpg 300w, https://www.docdigitales.com/blog/wp-content/uploads/2021/07/7.1-768x315.jpg 768w" sizes="(max-width: 730px) 100vw, 730px" /></figure></div>
            <div className="centerImage"><figure className="aligncenter is-resized"><img src="https://www.docdigitales.com/blog/wp-content/uploads/2021/07/8-1.png" alt="8 1" className="wp-image-6427" width="754" height="277" srcset="https://www.docdigitales.com/blog/wp-content/uploads/2021/07/8-1.png 964w, https://www.docdigitales.com/blog/wp-content/uploads/2021/07/8-1-300x110.png 300w, https://www.docdigitales.com/blog/wp-content/uploads/2021/07/8-1-768x283.png 768w" sizes="(max-width: 754px) 100vw, 754px" /></figure></div>
            <p><strong>Nota: Es importante tener las descargas activas en tu navegador ya que una vez confirmado se descargará el acuse en formato PDF y éste no se podrá recuperarse.</strong></p>
            <br />
            <p><strong> 8.-</strong> Por último ingresa nuevamente con tu <strong>Firma Electrónica</strong> para concluir y sellar este trámite. </p>
            <br />
            <div className="centerImage"><figure className="aligncenter is-resized"><img src="https://www.docdigitales.com/blog/wp-content/uploads/2021/08/Imagen1-1.png" alt="Imagen1 1" className="wp-image-6605" width="673" height="329" srcset="https://www.docdigitales.com/blog/wp-content/uploads/2021/08/Imagen1-1.png 935w, https://www.docdigitales.com/blog/wp-content/uploads/2021/08/Imagen1-1-300x147.png 300w, https://www.docdigitales.com/blog/wp-content/uploads/2021/08/Imagen1-1-768x376.png 768w" sizes="(max-width: 673px) 100vw, 673px" /></figure></div>
            <p><strong>9.-</strong> Una vez que ingresaste te indicará que tu trámite ha sido finalizado </p>
            <br />
            <div className="centerImage"><figure className="aligncenter is-resized"><img src="https://www.docdigitales.com/blog/wp-content/uploads/2021/07/9-1.png" alt="9 1" className="wp-image-6433" width="676" height="108" srcset="https://www.docdigitales.com/blog/wp-content/uploads/2021/07/9-1.png 962w, https://www.docdigitales.com/blog/wp-content/uploads/2021/07/9-1-300x48.png 300w, https://www.docdigitales.com/blog/wp-content/uploads/2021/07/9-1-768x123.png 768w" sizes="(max-width: 676px) 100vw, 676px" /></figure></div>
            <p style={{ textAlign: "center" }}><strong>Esperamos que esta información haya sido de ayuda.&nbsp;</strong><br />Con <a href="https://www.docdigitales.com/tuconta" target="_blank" rel="noreferrer noopener" aria-label="tuConta (abre en una nueva pestaña)">tuConta</a> de <a rel="noreferrer noopener" aria-label="docDigitales (abre en una nueva pestaña)" href="https://www.docdigitales.com/" target="_blank">docDigitales</a>, ¡Encárgate de tu Negocio, Nosotros de tu Contabilidad!</p>
            <br />
            <p style={{ textAlign: "center" }}>¿Quieres contratar <a href="https://www.docdigitales.com/tuconta" target="_blank" rel="noreferrer noopener" aria-label="tuConta (abre en una nueva pestaña)">tuConta</a>? contáctanos al 686 520 0503 o al correo electrónico&nbsp;<strong>contacto@docdigitales.com&nbsp;</strong><br />Visita nuestro sitio web&nbsp;<a href="http://www.docdigitales.com/tuconta">www.docdigitales.com</a><br /> Nuestro horario de atención es de 9:00 a 19:00&nbsp;<strong>hora Centro.</strong><br /></p>
            <br />
        </div>
    )
}

export default Article08;